### ISSUE TITLE
Build Error "Unable to find version '37.0.0' of package 'CefSharp.Common'

### ISSUE THREAD

**Issue by robertmuehsig** [cefsharp/CefSharp.MinimalExample#16]
I'm getting this build error with VS2013/2015 CTP6):

![image](https://cloud.githubusercontent.com/assets/756703/6503665/4a03dce8-c32f-11e4-9f87-a0fc14ab0d67.png)

Any hints?

**Comment by amaitland** [comment]
The `MinimalExample` project was using the old `Nuget Restore` method, I've just changed it to the newer one that better supports our project setup.

See https://github.com/cefsharp/CefSharp.MinimalExample/commit/d0282f03e6b891c4f0e403ed882a35d176f5310f

**Comment by robertmuehsig** [comment]
:+1: nice - works for me!
