### ISSUE TITLE
How to remove load bar?

### ISSUE THREAD

**Issue by cristiangiagante** [cefsharp/CefSharp.MinimalExample#18]
Hello i want to know how remover the little load bar from the left bottom corner.

Thanks

**Comment by amaitland** [comment]
From which example? Basically `CefSharp` is a framework, and as such you don't have to include features that aren't of interest to you.

**Comment by cristiangiagante** [comment]
minimal example wpf, i want remove the load bar that show "charging webpage progress"

**Comment by amaitland** [comment]
Remove the `ProgressBar` from the `xaml` and update the code accordingly.
