### ISSUE TITLE
Need more references as the project is not explorable as is...

### ISSUE THREAD

**Issue by Javaman2** [cefsharp/CefSharp.MinimalExample#20]
**The project does not come with these references:**

*CEFSharp
*CEFSharp.Core
*CefSharp.BrowserSubProcess.Cor
*CefSharp.Wpf

Please add them so we can experiment more with this excellent package.

**Comment by amaitland** [comment]
This project uses the `Nuget` packages to demo `CefSharp`. It demonstrates the same user experience you would have when installing the packages yourself.
