### ISSUE TITLE
Fix for the example code

### ISSUE THREAD

**Issue by feinstein** [cefsharp/CefSharp.MinimalExample#27]
Call me lazy on this one, but I don't want to clone and open a pull request for such a simple project.

On the Window XAML, just add this to correct the loading progress bar and displaying of the address text:

       <StatusBar Grid.Row="1">
            <ProgressBar HorizontalAlignment="Right"
                         IsIndeterminate="{Binding IsLoading, ElementName=Browser}"
                         Width="100"
                         Height="16"
                         Margin="3" />
            <Separator />
            
            <TextBlock Text="{Binding Address, ElementName=Browser}"/>
        </StatusBar>

Showing the mouse hovering link address will be A LOT more complicated using WPF and MVVM though.

**Comment by amaitland** [comment]
> Call me lazy on this one, but I don't want to clone and open a pull request for such a simple project.

If you submit a `PR` I'll happy hit merge, otherwise will have to wait until someone else submits one.

**Comment by feinstein** [comment]
Done in #28.

**Comment by amaitland** [comment]
Thanks, merged 👍
