### ISSUE TITLE
Display print screen not a browser

### ISSUE THREAD

**Issue by hasan3ysf** [cefsharp/CefSharp.MinimalExample#29]
may I did not understand the purpose of this, I run it, and it gave me a print screen of the google page with the note "CeSgarp was here" in the search bar, but I did not see any browser!

Is not it supposed to display the webpage as a browser?

**Comment by amaitland** [comment]
> may I did not understand the purpose of this

As per https://github.com/cefsharp/CefSharp.MinimalExample/blob/master/README.md there are three different examples. Run the one that's relevant to you.
