### ISSUE TITLE
JsDialogHandler - OnJsAlert results in vshost.exe crash, on Return from handler

### ISSUE THREAD

**Issue by prabindh** [cefsharp/CefSharp.MinimalExample#32]
OnJsAlert results in vshost.exe crash, on Return from handler. Code below. Parent is a form. What is the right way to setup the handler ? It does not crash if false is returned. Commenting the ShowTextInputForm() part does not help so not a threading issue. CEF# version 3.2785.1482 64b Win10, .NET 4.5.2

   public class JsDialogHandler : IJsDialogHandler
    {
        string result = "default";
        public bool OnJSDialog(IWebBrowser browserControl, IBrowser browser, string originUrl, 
            CefJsDialogType dialogType, string messageText, string defaultPromptText, 
            IJsDialogCallback callback, ref bool suppressMessage)
        {
            suppressMessage = true;
            if (dialogType == CefJsDialogType.Prompt)
            {
                parent.Invoke(new Action(() =>
                {
                    result = ShowTextInputForm(); // Show a form and get text input
                }));
               if(null != callback && !callback.IsDisposed)
                {
                    callback.Continue(true, result);
                }
            }
            else
            {
                MessageBox.Show(messageText, "Status", MessageBoxButtons.OKCancel, MessageBoxIcon.Asterisk);
            }
            return true;
        }

==>> After return, crashes.

**Comment by amaitland** [comment]
See https://github.com/cefsharp/CefSharp/issues/1891
