### ISSUE TITLE
browsersubprocess crashes

### ISSUE THREAD

**Issue by geduldig** [cefsharp/CefSharp.MinimalExample#33]
I am running the offscreen minimal example in VS2013u5 on Windows 7 with .NET 4.5.2 and get the error below. Example was compiled in Debug x64 with cef.redist.x64.3.2785.1482 and run from the IDE. 

![error](https://cloud.githubusercontent.com/assets/2967359/21401242/844ba158-c781-11e6-9780-d2103fb4fcab.png)

**Comment by amaitland** [comment]
See know issues https://github.com/cefsharp/CefSharp/releases/tag/v53.0.0
