### ISSUE TITLE
Bad Nuget for offscreen CefSharp

### ISSUE THREAD

**Issue by panthernet** [cefsharp/CefSharp.MinimalExample#35]
Hi, currently, after installing specified nuget i get tons of errors in a .NET 4.5.2 projects and references won't add by default. I can add them manually but they're marked bad. BUT! Projects compiles and run normally.

If i change platform to .NET 4.6 all is fine. That looks odd, not sure if it is on my side.

Tested on a NEW .NET 4.5.2 project. Please check it. Thanks.

**Comment by panthernet** [comment]
Nevermind. Were required to add new x86 or x64 solution platfrom.

**Comment by amaitland** [comment]
@panthernet The `CefSharp.MinimalExample` project doesn't provide any `Nuget` packages, it simply provides a working example. Did you experience a problem with the `CefSharp.MinimalExample` project it's self? If not then this isn't the place to be opening an issue.

In future please persevere a little longer before opening an issue, the `CefSharp.OffScreen` packages have been available for over a month, and have over 1000 downloads, the package structure hasn't changed in quite some time.

https://www.nuget.org/packages/CefSharp.OffScreen/
