### ISSUE TITLE
CefSharp and ChromiumWebBrowser references not found

### ISSUE THREAD

**Issue by vurso** [cefsharp/CefSharp.MinimalExample#38]
The source doesn't build unfortunately.

Downloaded as zip, extracted and started up in Visual Studio 2017 professional, did a nuget package restore but the IDE can't find references for CefSharp.OffScreen and ChromiumWebBrowser.

**Comment by vurso** [comment]
you're having a laugh this won't work with anything below .NET 4.6.1?

**Comment by merceyz** [comment]
Minimum supported version of .NET is v4.5.2.
You're more than welcome to build for a lower version.
