### ISSUE TITLE
Slow UI performance in WPF

### ISSUE THREAD

**Issue by krugertech** [cefsharp/CefSharp.MinimalExample#39]
WPF UI performance laggy on  1 year old i5 laptop.
The UI runs smoothly in WinForms.

**How to test:**
1. Run the CefSharp.MinimalExample WPF demo. 
2. Enter "Testing 123" in the google search box. 
3. Click the images link, to view images related to this search criteria.
4. Scroll your mouse wheel down and up and notice how responsive it feels. 
5. Repeat steps 2-4 for the WinForms demo and notice the difference.

**Comment by danielehrhardt** [comment]
Same here

**Comment by amaitland** [comment]
If the performance of the `WPF` control doesn't suite your needs then you'll have to use the `WinForms` version hosted in `WindowsFormsHost` control.

For more about how the `WPF` version renders see https://github.com/cefsharp/CefSharp/wiki/General-Usage#offscreenwpf

There will be some performance improvements in version `63`, see https://bitbucket.org/chromiumembedded/cef/commits/8f2fa9905f5b615b65b036106d762a37f0d4fcfa

Further questions read https://github.com/cefsharp/CefSharp#contact
