### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by MINGSON666** [cefsharp/CefSharp.MinimalExample#59]
Version:  CefSharp.MinimalExample 75.1.143

when I build the project CefSharp.MinimalExample.CefSharp.MinimalExample.Wpf, the error lists show

Your project does not reference ".NETFramework,Version=v4.5.2" framework. Add a reference to ".NETFramework,Version=v4.5.2" in the "TargetFrameworks" property of your project file and then re-run NuGet restore.	CefSharp.MinimalExample.Wpf

**Comment by amaitland** [comment]
> A minor drawback of this approach is that when you want to switch between the .NET Core and .NET Framework solutions, you might have to delete the existing obj folder to avoid errors from the build system.

As per https://github.com/cefsharp/CefSharp.MinimalExample/pull/57#issuecomment-529095198 you must delete the `obj` folder manually or perform a git cleanup.
