### ISSUE TITLE
core build by x86&single publish and run win7

### ISSUE THREAD

**Issue by huapiaoshuiliuxi** [cefsharp/CefSharp.MinimalExample#60]
![image](https://user-images.githubusercontent.com/59419847/71645317-878bc700-2d11-11ea-8428-646bfd3c5438.png)

the os by no .net framework environment.

![image](https://user-images.githubusercontent.com/59419847/71645247-5e1e6b80-2d10-11ea-9c2e-ff97086625f5.png)

**Comment by amaitland** [comment]
https://github.com/cefsharp/CefSharp.MinimalExample#net-core-support

**Comment by amaitland** [comment]
In future please ask questions on https://stackoverflow.com/questions/tagged/cefsharp

**Comment by huapiaoshuiliuxi** [comment]
> https://github.com/cefsharp/CefSharp.MinimalExample#net-core-support

3ks for your reply.
For reason :"CefSharp.BrowserSubprocess.exe". I should for waiting...
There are more limit on stackoverflow for me.
期待~并且期待.net Next.

**Comment by amaitland** [comment]
I only speak English. 

Stackoverflow is were questions should be asked, thanks.
